[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

lib_deps =
  ESP32Async/AsyncTCP @ ^3.3.2
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
  bblanchon/ArduinoJson @ ^7.1.0
  adafruit/DHT sensor library @ ^1.4.6
  knolleary/PubSubClient @ ^2.8

build_flags =
  -D CORE_DEBUG_LEVEL=2
  -D APP_VERSION=\"1.0.0\"
  ; Set to 1 to enable MQTT module
  -D ENABLE_MQTT=0
